# TCL File Generated by Component Editor 17.0
# Sat Dec 23 22:08:15 CET 2017
# DO NOT MODIFY


# 
# LCD_controller "LCD_controller" v1.0
# Lazzara L., Manzini A. 2017.12.23.22:08:15
# Display images stored on the DRAM on the LCD
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD_controller
# 
set_module_property DESCRIPTION "Display images stored on the DRAM on the LCD"
set_module_property NAME LCD_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Lazzara L., Manzini A."
set_module_property DISPLAY_NAME LCD_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file FIFO.vhd VHDL PATH ../../hdl/FIFO.vhd
add_fileset_file LCD_controller.vhd VHDL PATH ../../hdl/LCD_controller.vhd TOP_LEVEL_FILE
add_fileset_file LT24_interface.vhd VHDL PATH ../../hdl/LT24_interface.vhd
add_fileset_file Master_DMA.vhd VHDL PATH ../../hdl/Master_DMA.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point am_0
# 
add_interface am_0 avalon start
set_interface_property am_0 addressUnits SYMBOLS
set_interface_property am_0 associatedClock clock
set_interface_property am_0 associatedReset reset
set_interface_property am_0 bitsPerSymbol 8
set_interface_property am_0 burstOnBurstBoundariesOnly false
set_interface_property am_0 burstcountUnits WORDS
set_interface_property am_0 doStreamReads false
set_interface_property am_0 doStreamWrites false
set_interface_property am_0 holdTime 0
set_interface_property am_0 linewrapBursts false
set_interface_property am_0 maximumPendingReadTransactions 0
set_interface_property am_0 maximumPendingWriteTransactions 0
set_interface_property am_0 readLatency 0
set_interface_property am_0 readWaitTime 0
set_interface_property am_0 setupTime 0
set_interface_property am_0 timingUnits Cycles
set_interface_property am_0 writeWaitTime 0
set_interface_property am_0 ENABLED true
set_interface_property am_0 EXPORT_OF ""
set_interface_property am_0 PORT_NAME_MAP ""
set_interface_property am_0 CMSIS_SVD_VARIABLES ""
set_interface_property am_0 SVD_ADDRESS_GROUP ""

add_interface_port am_0 avm_address address Output 32
add_interface_port am_0 avm_read read Output 1
add_interface_port am_0 avm_readdata readdata Input 32
add_interface_port am_0 avm_waitrequest waitrequest Input 1
add_interface_port am_0 avm_byteenable byteenable Output 4
add_interface_port am_0 avm_burstcount burstcount Output 8
add_interface_port am_0 avm_readdatavalid readdatavalid Input 1


# 
# connection point as0
# 
add_interface as0 avalon end
set_interface_property as0 addressUnits WORDS
set_interface_property as0 associatedClock clock
set_interface_property as0 associatedReset reset
set_interface_property as0 bitsPerSymbol 8
set_interface_property as0 burstOnBurstBoundariesOnly false
set_interface_property as0 burstcountUnits WORDS
set_interface_property as0 explicitAddressSpan 0
set_interface_property as0 holdTime 0
set_interface_property as0 linewrapBursts false
set_interface_property as0 maximumPendingReadTransactions 0
set_interface_property as0 maximumPendingWriteTransactions 0
set_interface_property as0 readLatency 0
set_interface_property as0 readWaitTime 1
set_interface_property as0 setupTime 0
set_interface_property as0 timingUnits Cycles
set_interface_property as0 writeWaitTime 0
set_interface_property as0 ENABLED true
set_interface_property as0 EXPORT_OF ""
set_interface_property as0 PORT_NAME_MAP ""
set_interface_property as0 CMSIS_SVD_VARIABLES ""
set_interface_property as0 SVD_ADDRESS_GROUP ""

add_interface_port as0 avs_address address Input 2
add_interface_port as0 avs_write write Input 1
add_interface_port as0 avs_writedata writedata Input 32
add_interface_port as0 avs_read read Input 1
add_interface_port as0 avs_readdata readdata Output 32
add_interface_port as0 avs_waitrequest waitrequest Output 1
set_interface_assignment as0 embeddedsw.configuration.isFlash 0
set_interface_assignment as0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment as0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment as0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point LT24
# 
add_interface LT24 conduit end
set_interface_property LT24 associatedClock clock
set_interface_property LT24 associatedReset ""
set_interface_property LT24 ENABLED true
set_interface_property LT24 EXPORT_OF ""
set_interface_property LT24 PORT_NAME_MAP ""
set_interface_property LT24 CMSIS_SVD_VARIABLES ""
set_interface_property LT24 SVD_ADDRESS_GROUP ""

add_interface_port LT24 csx csx Output 1
add_interface_port LT24 data data Output 16
add_interface_port LT24 dcx dcx Output 1
add_interface_port LT24 wrx wrx Output 1
add_interface_port LT24 LCD_on lcd_on Output 1
add_interface_port LT24 LCD_resn lcd_resn Output 1

